# 1 "data/maps/SootopolisCity_House5/scripts.pory"

# 2 "data/maps/SootopolisCity_House5/scripts.pory"
SootopolisCity_House5_MapScripts::
# 3 "data/maps/SootopolisCity_House5/scripts.pory"
	.byte 0
# 4 "data/maps/SootopolisCity_House5/scripts.pory"

# 5 "data/maps/SootopolisCity_House5/scripts.pory"
SootopolisCity_House5_EventScript_Maniac::
# 6 "data/maps/SootopolisCity_House5/scripts.pory"
	msgbox SootopolisCity_House5_Text_SootopolisMtPyreConnection, MSGBOX_NPC
# 7 "data/maps/SootopolisCity_House5/scripts.pory"
	end
# 8 "data/maps/SootopolisCity_House5/scripts.pory"

# 9 "data/maps/SootopolisCity_House5/scripts.pory"
SootopolisCity_House5_EventScript_Girl::
# 10 "data/maps/SootopolisCity_House5/scripts.pory"
	msgbox SootopolisCity_House5_Text_BrotherUsedToStudySea, MSGBOX_NPC
# 11 "data/maps/SootopolisCity_House5/scripts.pory"
	end
# 12 "data/maps/SootopolisCity_House5/scripts.pory"

# 13 "data/maps/SootopolisCity_House5/scripts.pory"
SootopolisCity_House5_Text_SootopolisMtPyreConnection:
# 14 "data/maps/SootopolisCity_House5/scripts.pory"
	.string "There appears to be some connection\n"
# 15 "data/maps/SootopolisCity_House5/scripts.pory"
	.string "between SOOTOPOLIS and MT. PYRE.\p"
# 16 "data/maps/SootopolisCity_House5/scripts.pory"
	.string "My friends and I did some research on\n"
# 17 "data/maps/SootopolisCity_House5/scripts.pory"
	.string "it at the lab where I used to work.$"
# 18 "data/maps/SootopolisCity_House5/scripts.pory"

# 19 "data/maps/SootopolisCity_House5/scripts.pory"
SootopolisCity_House5_Text_BrotherUsedToStudySea:
# 20 "data/maps/SootopolisCity_House5/scripts.pory"
	.string "My big brother used to study the sea.$"
