# 1 "data/maps/TrainerHill_1F/scripts.pory"

# 2 "data/maps/TrainerHill_1F/scripts.pory"
TrainerHill_1F_MapScripts::
# 3 "data/maps/TrainerHill_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, TrainerHill_OnResume
# 4 "data/maps/TrainerHill_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, TrainerHill_OnWarp
# 5 "data/maps/TrainerHill_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, TrainerHill_OnFrame
# 6 "data/maps/TrainerHill_1F/scripts.pory"
	.byte 0
