# 1 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 2 "data/maps/LilycoveCity_ContestHall/scripts.pory"
@ VAR_LAST_TALKED would have made all these direct references unnecessary
# 3 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_SMART_MC, 4
# 4 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_SMART_JUDGE, 5
# 5 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_SMART_CONTESTANT_1, 6
# 6 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_SMART_CONTESTANT_2, 7
# 7 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_SMART_CONTESTANT_3, 8
# 8 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_SMART_CONTESTANT_4, 9
# 9 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_SMART_AUDIENCE_4, 11
# 10 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_SMART_AUDIENCE_2, 12
# 11 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_BEAUTY_MC, 13
# 12 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_BEAUTY_JUDGE, 14
# 13 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_BEAUTY_CONTESTANT_1, 15
# 14 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_BEAUTY_CONTESTANT_2, 16
# 15 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_BEAUTY_CONTESTANT_3, 17
# 16 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_BEAUTY_CONTESTANT_4, 18
# 17 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_BEAUTY_AUDIENCE_1, 19
# 18 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_BEAUTY_AUDIENCE_3, 20
# 19 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_BEAUTY_AUDIENCE_2, 21
# 20 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_SMART_AUDIENCE_3, 22
# 21 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_CUTE_MC, 23
# 22 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_CUTE_JUDGE, 24
# 23 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_CUTE_CONTESTANT_1, 25
# 24 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_CUTE_CONTESTANT_2, 26
# 25 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_CUTE_CONTESTANT_3, 27
# 26 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_CUTE_CONTESTANT_4, 28
# 27 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_CUTE_AUDIENCE_1, 29
# 28 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_CUTE_AUDIENCE_3, 30
# 29 "data/maps/LilycoveCity_ContestHall/scripts.pory"
.set LOCALID_CUTE_AUDIENCE_2, 31
# 30 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 31 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_MapScripts::
# 32 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.byte 0
# 33 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 34 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_Boy1::
# 35 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_TodayWonSmartnessContest, MSGBOX_NPC
# 36 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 37 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 38 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_Boy2::
# 39 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_EnteredBunchOfContests, MSGBOX_NPC
# 40 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 41 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 42 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_Girl::
# 43 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_ManWhoWonEarlierHadPokeblocks, MSGBOX_NPC
# 44 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 45 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 46 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_Sailor::
# 47 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_IsntThisPlaceHumongous, MSGBOX_NPC
# 48 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 49 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 50 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_SmartContestMC::
# 51 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lock
# 52 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	faceplayer
# 53 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_GiveItBestSmartAppeal, MSGBOX_DEFAULT
# 54 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 55 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_SMART_MC, Common_Movement_FaceOriginalDirection
# 56 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 57 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	release
# 58 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 59 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 60 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_SmartContestJudge::
# 61 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lock
# 62 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	faceplayer
# 63 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_AreYouEnjoyingThisContest, MSGBOX_DEFAULT
# 64 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 65 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_SMART_JUDGE, Common_Movement_FaceOriginalDirection
# 66 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 67 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	release
# 68 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 69 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 70 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_SmartContestant1::
# 71 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lock
# 72 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	faceplayer
# 73 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_EnteredWrongContest, MSGBOX_DEFAULT
# 74 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 75 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_SMART_CONTESTANT_1, Common_Movement_FaceOriginalDirection
# 76 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 77 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	release
# 78 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 79 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 80 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_SmartContestant2::
# 81 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lock
# 82 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	faceplayer
# 83 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_RaisedMonToBeSmart, MSGBOX_DEFAULT
# 84 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 85 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_SMART_CONTESTANT_2, Common_Movement_FaceOriginalDirection
# 86 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 87 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	release
# 88 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 89 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 90 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_SmartContestant3::
# 91 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lock
# 92 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	faceplayer
# 93 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_IfMonPullsSmartMoveNext, MSGBOX_DEFAULT
# 94 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 95 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_SMART_CONTESTANT_3, Common_Movement_FaceOriginalDirection
# 96 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 97 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	release
# 98 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 99 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 100 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_SmartContestant4::
# 101 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lock
# 102 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	faceplayer
# 103 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_DontAppreciateCuteLeechLife, MSGBOX_DEFAULT
# 104 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 105 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_SMART_CONTESTANT_4, Common_Movement_FaceOriginalDirection
# 106 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 107 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	release
# 108 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 109 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 110 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_SmartContestAudience1::
# 111 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_YoureBeautifulGrandpa, MSGBOX_SIGN
# 112 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 113 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 114 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_SmartContestAudience2::
# 115 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lock
# 116 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	faceplayer
# 117 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_AllSeemToUseDifferentMoves, MSGBOX_DEFAULT
# 118 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 119 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_SMART_AUDIENCE_2, Common_Movement_FaceOriginalDirection
# 120 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 121 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	release
# 122 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 123 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 124 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_SmartContestAudience3::
# 125 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lock
# 126 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	faceplayer
# 127 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_PokemonSmarterThanTrainers, MSGBOX_DEFAULT
# 128 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 129 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_SMART_AUDIENCE_3, Common_Movement_FaceOriginalDirection
# 130 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 131 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	release
# 132 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 133 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 134 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_SmartContestAudience4::
# 135 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lock
# 136 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	faceplayer
# 137 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_StillLoveSmartnessContests, MSGBOX_DEFAULT
# 138 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 139 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_SMART_AUDIENCE_4, Common_Movement_FaceOriginalDirection
# 140 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 141 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	release
# 142 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 143 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 144 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_BeautyContestMC::
# 145 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lock
# 146 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	faceplayer
# 147 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_AreYouEnteringBeautyContest, MSGBOX_DEFAULT
# 148 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 149 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_BEAUTY_MC, Common_Movement_FaceOriginalDirection
# 150 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 151 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	release
# 152 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 153 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 154 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_BeautyContestJudge::
# 155 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lock
# 156 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	faceplayer
# 157 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_EveryPokemonPristineBeauty, MSGBOX_DEFAULT
# 158 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 159 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_BEAUTY_JUDGE, Common_Movement_FaceOriginalDirection
# 160 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 161 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	release
# 162 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 163 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 164 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_BeautyContestant1::
# 165 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lock
# 166 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	faceplayer
# 167 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_EyesWillBeGluedToMyBeauty, MSGBOX_DEFAULT
# 168 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 169 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_BEAUTY_CONTESTANT_1, Common_Movement_FaceOriginalDirection
# 170 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 171 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	release
# 172 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 173 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 174 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_BeautyContestant2::
# 175 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lock
# 176 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	faceplayer
# 177 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_OverdidGrooming, MSGBOX_DEFAULT
# 178 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 179 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_BEAUTY_CONTESTANT_2, Common_Movement_FaceOriginalDirection
# 180 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 181 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	release
# 182 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 183 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 184 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_BeautyContestant3::
# 185 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lock
# 186 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	faceplayer
# 187 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_JudgeWontSeeAuroraBeam, MSGBOX_DEFAULT
# 188 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 189 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_BEAUTY_CONTESTANT_3, Common_Movement_FaceOriginalDirection
# 190 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 191 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	release
# 192 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 193 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 194 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_BeautyContestant4::
# 195 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lock
# 196 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	faceplayer
# 197 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_PokemonLooksLikeYoungerMe, MSGBOX_DEFAULT
# 198 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 199 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_BEAUTY_CONTESTANT_4, Common_Movement_FaceOriginalDirection
# 200 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 201 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	release
# 202 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 203 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 204 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_BeautyContestAudience1::
# 205 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lock
# 206 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	faceplayer
# 207 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_WinBeautyContestMakesMeHappy, MSGBOX_DEFAULT
# 208 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 209 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_BEAUTY_AUDIENCE_1, Common_Movement_FaceOriginalDirection
# 210 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 211 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	release
# 212 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 213 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 214 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_BeautyContestAudience2::
# 215 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lock
# 216 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	faceplayer
# 217 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_GanderAtAllThosePrettyPokemon, MSGBOX_DEFAULT
# 218 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 219 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_BEAUTY_AUDIENCE_2, Common_Movement_FaceOriginalDirection
# 220 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 221 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	release
# 222 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 223 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 224 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_BeautyContestAudience3::
# 225 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lock
# 226 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	faceplayer
# 227 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_CantWinOnBeautyAlone, MSGBOX_DEFAULT
# 228 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 229 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_BEAUTY_AUDIENCE_3, Common_Movement_FaceOriginalDirection
# 230 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 231 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	release
# 232 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 233 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 234 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_CuteContestMC::
# 235 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lock
# 236 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	faceplayer
# 237 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_InTheMiddleOfContest, MSGBOX_DEFAULT
# 238 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 239 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_CUTE_MC, Common_Movement_FaceOriginalDirection
# 240 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 241 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	release
# 242 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 243 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 244 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_CuteContestJudge::
# 245 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lock
# 246 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	faceplayer
# 247 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_SuchCharmingCuteAppeals, MSGBOX_DEFAULT
# 248 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 249 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_CUTE_JUDGE, Common_Movement_FaceOriginalDirection
# 250 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 251 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	release
# 252 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 253 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 254 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_CuteContestant1::
# 255 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lock
# 256 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	faceplayer
# 257 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_MyAzurillWasDistracted, MSGBOX_DEFAULT
# 258 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 259 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_CUTE_CONTESTANT_1, Common_Movement_FaceOriginalDirection
# 260 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 261 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	release
# 262 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 263 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 264 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_CuteContestant2::
# 265 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lock
# 266 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	faceplayer
# 267 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_NeverWonBattleButContest, MSGBOX_DEFAULT
# 268 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 269 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_CUTE_CONTESTANT_2, Common_Movement_FaceOriginalDirection
# 270 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 271 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	release
# 272 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 273 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 274 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_CuteContestant3::
# 275 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lock
# 276 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	faceplayer
# 277 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_PetalDanceIsMarvel, MSGBOX_DEFAULT
# 278 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 279 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_CUTE_CONTESTANT_3, Common_Movement_FaceOriginalDirection
# 280 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 281 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	release
# 282 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 283 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 284 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_CuteContestant4::
# 285 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lock
# 286 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	faceplayer
# 287 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_MyMonAppealSoMuchCuter, MSGBOX_DEFAULT
# 288 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 289 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_CUTE_CONTESTANT_4, Common_Movement_FaceOriginalDirection
# 290 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 291 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	release
# 292 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 293 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 294 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_CuteContestAudience1::
# 295 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lockall
# 296 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_CUTE_AUDIENCE_1, Common_Movement_FacePlayer
# 297 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 298 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_MyChildIsInContest, MSGBOX_DEFAULT
# 299 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 300 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_CUTE_AUDIENCE_1, Common_Movement_FaceOriginalDirection
# 301 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 302 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	delay 25
# 303 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_ComeOnDear, MSGBOX_DEFAULT
# 304 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	releaseall
# 305 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 306 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 307 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_CuteContestAudience2::
# 308 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lock
# 309 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	faceplayer
# 310 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_WantCuteMonOfMyOwn, MSGBOX_DEFAULT
# 311 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 312 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_CUTE_AUDIENCE_2, Common_Movement_FaceOriginalDirection
# 313 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 314 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	release
# 315 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 316 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 317 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_CuteContestAudience3::
# 318 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	lock
# 319 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	faceplayer
# 320 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_ThatGirlThereIsCutest, MSGBOX_DEFAULT
# 321 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	closemessage
# 322 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	applymovement LOCALID_CUTE_AUDIENCE_3, Common_Movement_FaceOriginalDirection
# 323 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	waitmovement 0
# 324 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	release
# 325 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 326 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 327 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_BeautyStageSign::
# 328 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_BeautyContestStage, MSGBOX_SIGN
# 329 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 330 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 331 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_CuteStageSign::
# 332 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_CuteContestStage, MSGBOX_SIGN
# 333 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 334 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 335 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_EventScript_SmartStageSign::
# 336 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	msgbox LilycoveCity_ContestHall_Text_SmartContestStage, MSGBOX_SIGN
# 337 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	end
# 338 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 339 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_TodayWonSmartnessContest:
# 340 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "This POKéMON won the BEAUTY CONTEST\n"
# 341 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "here before.\p"
# 342 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Well, guess what? Today, I made it\n"
# 343 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "win a SMARTNESS CONTEST!\p"
# 344 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "My abilities scare even me…$"
# 345 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 346 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_EnteredBunchOfContests:
# 347 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "I've entered a bunch of CONTESTS,\n"
# 348 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "so I'm seeing how things work.\p"
# 349 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "If you're in a COOLNESS CONTEST,\n"
# 350 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "cool moves go over as appeals.\p"
# 351 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "But smart moves and cute moves\n"
# 352 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "don't go over well, for instance.$"
# 353 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 354 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_ManWhoWonEarlierHadPokeblocks:
# 355 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "That young man who won earlier had\n"
# 356 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "a whole bunch of different {POKEBLOCK}S.\p"
# 357 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Can you win if you had that many\n"
# 358 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "of those things?$"
# 359 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 360 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_IsntThisPlaceHumongous:
# 361 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Whoa, isn't this place humongous!\p"
# 362 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "The tension in the air… It's not\n"
# 363 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "like a CONTEST hall in the sticks.$"
# 364 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 365 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_GiveItBestSmartAppeal:
# 366 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "MC: Okay, SMART POKéMON and their\n"
# 367 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "TRAINERS, are you ready?!\p"
# 368 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Give it your best showing!\n"
# 369 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Let's appeal!$"
# 370 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 371 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_AreYouEnjoyingThisContest:
# 372 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "JUDGE: Are you enjoying this CONTEST?\p"
# 373 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Come back with three friends, and\n"
# 374 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "all of you may enter a CONTEST!$"
# 375 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 376 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_EnteredWrongContest:
# 377 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Ayayayay…\n"
# 378 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "I entered the wrong CONTEST.\p"
# 379 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "I entered this tough POKéMON in\n"
# 380 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "the SMARTNESS CONTEST…\p"
# 381 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Come on, wow them with a smart-looking\n"
# 382 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "ROCK SMASH.$"
# 383 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 384 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_RaisedMonToBeSmart:
# 385 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "I've spent many a year, and all my\n"
# 386 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "wisdom besides, raising this POKéMON\l"
# 387 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "to be smart.\p"
# 388 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "It won't be easily bested by some\n"
# 389 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "young pup's POKéMON.\p"
# 390 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "My dear wife, are you seeing this?$"
# 391 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 392 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_IfMonPullsSmartMoveNext:
# 393 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "There it is!\p"
# 394 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "If my POKéMON pulls a smart move next,\n"
# 395 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "the audience's excitement will peak!$"
# 396 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 397 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_DontAppreciateCuteLeechLife:
# 398 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Oh, dear, no!\p"
# 399 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "My darling ZUBAT's LEECH LIFE is so\n"
# 400 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "cute I kept using it over and over!\p"
# 401 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "But these mean people don't appreciate\n"
# 402 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "it at all!$"
# 403 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 404 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_YoureBeautifulGrandpa:
# 405 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Kiyaaah! You're beautiful, Grandpa!$"
# 406 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 407 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_AllSeemToUseDifferentMoves:
# 408 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Even when TRAINERS enter the same\n"
# 409 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "kind of POKéMON, they all seem to use\l"
# 410 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "different moves for appeals.\p"
# 411 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "It's just like the way people have\n"
# 412 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "different styles for battling.$"
# 413 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 414 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_PokemonSmarterThanTrainers:
# 415 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "I think the POKéMON look smarter\n"
# 416 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "than their TRAINERS. By a lot.$"
# 417 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 418 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_StillLoveSmartnessContests:
# 419 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "When all's said and done, I still love\n"
# 420 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "SMARTNESS CONTESTS.\p"
# 421 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "That intellectual green color…\n"
# 422 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "It's so… So… Cool.$"
# 423 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 424 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_AreYouEnteringBeautyContest:
# 425 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "MC: Are you entering the BEAUTY\n"
# 426 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "CONTEST, too? Good luck!$"
# 427 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 428 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_EveryPokemonPristineBeauty:
# 429 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "JUDGE: Ah, every POKéMON here is\n"
# 430 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "a model of pristine beauty!\p"
# 431 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Why, I almost forgot to score them!$"
# 432 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 433 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_EyesWillBeGluedToMyBeauty:
# 434 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "A POKéMON this beautiful…\n"
# 435 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "There isn't another one like it.\p"
# 436 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Everyone's eyes will be glued to\n"
# 437 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "my beauty.$"
# 438 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 439 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_OverdidGrooming:
# 440 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Waaaah!\p"
# 441 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "I brushed and groomed my POKéMON\n"
# 442 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "carefully for this CONTEST…\p"
# 443 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "But I overdid it…\n"
# 444 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "My POKéMON's coat turned all scraggly…\p"
# 445 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "What should I do?$"
# 446 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 447 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_JudgeWontSeeAuroraBeam:
# 448 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "This AURORA BEAM is so dazzling,\n"
# 449 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "the JUDGE won't be able to see it.\p"
# 450 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Uh, wait a second…\n"
# 451 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "That'll be meaningless, then!$"
# 452 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 453 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_PokemonLooksLikeYoungerMe:
# 454 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "This pretty POKéMON looks just like\n"
# 455 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "me when I was younger.\p"
# 456 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Right when I said that, my husband\n"
# 457 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "spewed the coffee he was drinking.\p"
# 458 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Did I say something funny?$"
# 459 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 460 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_WinBeautyContestMakesMeHappy:
# 461 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "You know, if I win at a BEAUTY\n"
# 462 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "CONTEST, sure it makes me\l"
# 463 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "happy. More than usual, anyway.$"
# 464 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 465 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_GanderAtAllThosePrettyPokemon:
# 466 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Wahahahah!\p"
# 467 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Will you take a gander at all those\n"
# 468 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "pretty POKéMON!\l"
# 469 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "I just love this sort of glitz!$"
# 470 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 471 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_CantWinOnBeautyAlone:
# 472 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "You can't always win on just beauty\n"
# 473 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "alone.\p"
# 474 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "You have to groom your POKéMON so\n"
# 475 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "it's nice and glossy like mine.$"
# 476 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 477 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_InTheMiddleOfContest:
# 478 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "MC: Uh-oh! Hello!\n"
# 479 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "We're in the middle of a CONTEST!\p"
# 480 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Please enter at our registration\n"
# 481 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "counter and come out, okay?$"
# 482 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 483 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_SuchCharmingCuteAppeals:
# 484 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "JUDGE: Oh, such charming and cute\n"
# 485 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "appeals!\p"
# 486 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Oh, my goodness! What a perfectly\n"
# 487 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "adorable WATER SPORT appeal!$"
# 488 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 489 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_MyAzurillWasDistracted:
# 490 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Oh, no… My sweet AZURILL was\n"
# 491 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "distracted by another POKéMON.$"
# 492 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 493 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_NeverWonBattleButContest:
# 494 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "My POKéMON has never won in a battle,\n"
# 495 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "but put it in a CONTEST and look out!$"
# 496 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 497 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_PetalDanceIsMarvel:
# 498 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "My POKéMON's PETAL DANCE is a marvel\n"
# 499 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "of elegance.\p"
# 500 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "I won't let anyone disturb its\n"
# 501 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "performance.$"
# 502 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 503 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_MyMonAppealSoMuchCuter:
# 504 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Everyone's POKéMON are very cute.\p"
# 505 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "However, if my POKéMON were to make\n"
# 506 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "a cute appeal…\p"
# 507 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "I'm sure that it would be so much \n"
# 508 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "cuter than the others.$"
# 509 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 510 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_MyChildIsInContest:
# 511 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "My child is in this CONTEST.$"
# 512 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 513 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_ComeOnDear:
# 514 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Come on, dear. Go for it!\n"
# 515 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Your POKéMON is the best!$"
# 516 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 517 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_ThatGirlThereIsCutest:
# 518 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "I think that girl over there is\n"
# 519 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "the cutest of the lot.\p"
# 520 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "What's that? They're judging\n"
# 521 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "POKéMON by their looks?$"
# 522 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 523 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_WantCuteMonOfMyOwn:
# 524 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Ohh, seeing all these cute POKéMON,\n"
# 525 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "they make we want to get my own!\p"
# 526 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "I'm going to go catch some!$"
# 527 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 528 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_BeautyContestStage:
# 529 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "BEAUTY CONTEST STAGE\n"
# 530 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "BE ALLURED BY BEAUTIFUL POKéMON!$"
# 531 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 532 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_CuteContestStage:
# 533 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "CUTENESS CONTEST STAGE\n"
# 534 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "BE CHARMED BY CUTE POKéMON!$"
# 535 "data/maps/LilycoveCity_ContestHall/scripts.pory"

# 536 "data/maps/LilycoveCity_ContestHall/scripts.pory"
LilycoveCity_ContestHall_Text_SmartContestStage:
# 537 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "SMARTNESS CONTEST STAGE\n"
# 538 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "BE IMPRESSED BY SMART POKéMON!$"
