# 1 "data/maps/SafariZone_RestHouse/scripts.pory"

# 2 "data/maps/SafariZone_RestHouse/scripts.pory"
SafariZone_RestHouse_MapScripts::
# 3 "data/maps/SafariZone_RestHouse/scripts.pory"
	.byte 0
# 4 "data/maps/SafariZone_RestHouse/scripts.pory"

# 5 "data/maps/SafariZone_RestHouse/scripts.pory"
SafariZone_RestHouse_EventScript_Youngster::
# 6 "data/maps/SafariZone_RestHouse/scripts.pory"
	msgbox SafariZone_RestHouse_Text_Youngster, MSGBOX_NPC
# 7 "data/maps/SafariZone_RestHouse/scripts.pory"
	end
# 8 "data/maps/SafariZone_RestHouse/scripts.pory"

# 9 "data/maps/SafariZone_RestHouse/scripts.pory"
SafariZone_RestHouse_EventScript_PsychicM::
# 10 "data/maps/SafariZone_RestHouse/scripts.pory"
	msgbox SafariZone_RestHouse_Text_PsychicM, MSGBOX_NPC
# 11 "data/maps/SafariZone_RestHouse/scripts.pory"
	end
# 12 "data/maps/SafariZone_RestHouse/scripts.pory"

# 13 "data/maps/SafariZone_RestHouse/scripts.pory"
SafariZone_RestHouse_EventScript_FatMan::
# 14 "data/maps/SafariZone_RestHouse/scripts.pory"
	msgbox SafariZone_RestHouse_Text_FatMan, MSGBOX_NPC
# 15 "data/maps/SafariZone_RestHouse/scripts.pory"
	end
