# 1 "data/maps/SootopolisCity_House7/scripts.pory"

# 2 "data/maps/SootopolisCity_House7/scripts.pory"
SootopolisCity_House7_MapScripts::
# 3 "data/maps/SootopolisCity_House7/scripts.pory"
	.byte 0
# 4 "data/maps/SootopolisCity_House7/scripts.pory"

# 5 "data/maps/SootopolisCity_House7/scripts.pory"
SootopolisCity_House7_EventScript_OldMan::
# 6 "data/maps/SootopolisCity_House7/scripts.pory"
	msgbox SootopolisCity_House7_Text_CityFromEruptedVolcano, MSGBOX_NPC
# 7 "data/maps/SootopolisCity_House7/scripts.pory"
	end
# 8 "data/maps/SootopolisCity_House7/scripts.pory"

# 9 "data/maps/SootopolisCity_House7/scripts.pory"
SootopolisCity_House7_EventScript_PokefanF::
# 10 "data/maps/SootopolisCity_House7/scripts.pory"
	msgbox SootopolisCity_House7_Text_CaveMadeToKeepSomething, MSGBOX_NPC
# 11 "data/maps/SootopolisCity_House7/scripts.pory"
	end
# 12 "data/maps/SootopolisCity_House7/scripts.pory"

# 13 "data/maps/SootopolisCity_House7/scripts.pory"
SootopolisCity_House7_Text_CityFromEruptedVolcano:
# 14 "data/maps/SootopolisCity_House7/scripts.pory"
	.string "An underwater volcano erupted and\n"
# 15 "data/maps/SootopolisCity_House7/scripts.pory"
	.string "forced itself up from the depths.\p"
# 16 "data/maps/SootopolisCity_House7/scripts.pory"
	.string "Its crater emerged from the sea and\n"
# 17 "data/maps/SootopolisCity_House7/scripts.pory"
	.string "became filled with rainwater.\p"
# 18 "data/maps/SootopolisCity_House7/scripts.pory"
	.string "That's how SOOTOPOLIS CITY came into\n"
# 19 "data/maps/SootopolisCity_House7/scripts.pory"
	.string "being.$"
# 20 "data/maps/SootopolisCity_House7/scripts.pory"

# 21 "data/maps/SootopolisCity_House7/scripts.pory"
SootopolisCity_House7_Text_CaveMadeToKeepSomething:
# 22 "data/maps/SootopolisCity_House7/scripts.pory"
	.string "The cave that links SOOTOPOLIS and\n"
# 23 "data/maps/SootopolisCity_House7/scripts.pory"
	.string "the outside world…\p"
# 24 "data/maps/SootopolisCity_House7/scripts.pory"
	.string "It seems as if the cave was made to\n"
# 25 "data/maps/SootopolisCity_House7/scripts.pory"
	.string "keep something from getting out.\p"
# 26 "data/maps/SootopolisCity_House7/scripts.pory"
	.string "Or am I just imagining things?$"
