# 1 "data/maps/Underwater_SootopolisCity/scripts.pory"

# 2 "data/maps/Underwater_SootopolisCity/scripts.pory"
Underwater_SootopolisCity_MapScripts::
# 3 "data/maps/Underwater_SootopolisCity/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, Underwater_SootopolisCity_OnResume
# 4 "data/maps/Underwater_SootopolisCity/scripts.pory"
	.byte 0
# 5 "data/maps/Underwater_SootopolisCity/scripts.pory"

# 6 "data/maps/Underwater_SootopolisCity/scripts.pory"
Underwater_SootopolisCity_OnResume:
# 7 "data/maps/Underwater_SootopolisCity/scripts.pory"
	setdivewarp MAP_SOOTOPOLIS_CITY, 29, 53
# 8 "data/maps/Underwater_SootopolisCity/scripts.pory"
	end
