# 1 "data/maps/SlateportCity_House/scripts.pory"

# 2 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_MapScripts::
# 3 "data/maps/SlateportCity_House/scripts.pory"
	.byte 0
# 4 "data/maps/SlateportCity_House/scripts.pory"

# 5 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_EventScript_PokefanM::
# 6 "data/maps/SlateportCity_House/scripts.pory"
	msgbox SlateportCity_House_Text_NatureToDoWithStatGains, MSGBOX_NPC
# 7 "data/maps/SlateportCity_House/scripts.pory"
	end
# 8 "data/maps/SlateportCity_House/scripts.pory"

# 9 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_EventScript_Girl::
# 10 "data/maps/SlateportCity_House/scripts.pory"
	msgbox SlateportCity_House_Text_MustBeGoingToBattleTent, MSGBOX_NPC
# 11 "data/maps/SlateportCity_House/scripts.pory"
	end
# 12 "data/maps/SlateportCity_House/scripts.pory"

# 13 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_Text_NatureToDoWithStatGains:
# 14 "data/maps/SlateportCity_House/scripts.pory"
	.string "My POKéMON has a HASTY nature.\p"
# 15 "data/maps/SlateportCity_House/scripts.pory"
	.string "It has higher SPEED compared to\n"
# 16 "data/maps/SlateportCity_House/scripts.pory"
	.string "my other POKéMON.\p"
# 17 "data/maps/SlateportCity_House/scripts.pory"
	.string "Maybe their nature has something to\n"
# 18 "data/maps/SlateportCity_House/scripts.pory"
	.string "do with the stat gains of POKéMON.$"
# 19 "data/maps/SlateportCity_House/scripts.pory"

# 20 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_Text_MustBeGoingToBattleTent:
# 21 "data/maps/SlateportCity_House/scripts.pory"
	.string "You're a TRAINER, aren't you?\p"
# 22 "data/maps/SlateportCity_House/scripts.pory"
	.string "Since you came to SLATEPORT CITY,\n"
# 23 "data/maps/SlateportCity_House/scripts.pory"
	.string "you must be going to the BATTLE TENT.$"
