# 1 "data/maps/PetalburgCity_House1/scripts.pory"

# 2 "data/maps/PetalburgCity_House1/scripts.pory"
PetalburgCity_House1_MapScripts::
# 3 "data/maps/PetalburgCity_House1/scripts.pory"
	.byte 0
# 4 "data/maps/PetalburgCity_House1/scripts.pory"

# 5 "data/maps/PetalburgCity_House1/scripts.pory"
PetalburgCity_House1_EventScript_Man::
# 6 "data/maps/PetalburgCity_House1/scripts.pory"
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
# 7 "data/maps/PetalburgCity_House1/scripts.pory"
	end
# 8 "data/maps/PetalburgCity_House1/scripts.pory"

# 9 "data/maps/PetalburgCity_House1/scripts.pory"
PetalburgCity_House1_EventScript_Woman::
# 10 "data/maps/PetalburgCity_House1/scripts.pory"
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
# 11 "data/maps/PetalburgCity_House1/scripts.pory"
	end
# 12 "data/maps/PetalburgCity_House1/scripts.pory"

# 13 "data/maps/PetalburgCity_House1/scripts.pory"
PetalburgCity_House1_Text_TravelingIsWonderful:
# 14 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "Traveling is wonderful!\p"
# 15 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "When I was young, I roamed the seas\n"
# 16 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "and the mountains!$"
# 17 "data/maps/PetalburgCity_House1/scripts.pory"

# 18 "data/maps/PetalburgCity_House1/scripts.pory"
PetalburgCity_House1_Text_GoOnAdventure:
# 19 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "Sigh…\p"
# 20 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "I wish I could go on an adventure\n"
# 21 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "with some POKéMON…\p"
# 22 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "Crawl through some damp grass…\n"
# 23 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "Climb rocky, rugged mountains…\p"
# 24 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "Cross the raging seas…\n"
# 25 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "Wander about in dark caves…\p"
# 26 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "And, sometimes, even get a little\n"
# 27 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "homesick…\p"
# 28 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "It must be fabulous to travel!$"
