# 1 "data/maps/RustboroCity_Flat2_3F/scripts.pory"

# 2 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
RustboroCity_Flat2_3F_MapScripts::
# 3 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	.byte 0
# 4 "data/maps/RustboroCity_Flat2_3F/scripts.pory"

# 5 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
RustboroCity_Flat2_3F_EventScript_DevonEmployee::
# 6 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	msgbox RustboroCity_Flat2_3F_Text_PresidentCollectsRareStones, MSGBOX_NPC
# 7 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	end
# 8 "data/maps/RustboroCity_Flat2_3F/scripts.pory"

# 9 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
RustboroCity_Flat2_3F_EventScript_Woman::
# 10 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	msgbox RustboroCity_Flat2_3F_Text_PresidentsSonAlsoCollectsRareStones, MSGBOX_NPC
# 11 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	end
# 12 "data/maps/RustboroCity_Flat2_3F/scripts.pory"

# 13 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
RustboroCity_Flat2_3F_Text_PresidentCollectsRareStones:
# 14 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	.string "DEVON's PRESIDENT likes to collect\n"
# 15 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	.string "rare stones.$"
# 16 "data/maps/RustboroCity_Flat2_3F/scripts.pory"

# 17 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
RustboroCity_Flat2_3F_Text_PresidentsSonAlsoCollectsRareStones:
# 18 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	.string "I think the PRESIDENT's son also\n"
# 19 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	.string "collects rare stones.$"
