# 1 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 2 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
.set LOCALID_SS_TIDAL, 2
# 3 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
.set LOCALID_FERRY_ATTENDANT, 3
# 4 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
.set LOCALID_MANIAC_1, 9
# 5 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
.set LOCALID_MANIAC_2, 10
# 6 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
.set LOCALID_GIRL, 12
# 7 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
.set LOCALID_CAMPER, 14
# 8 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
.set LOCALID_FISHERMAN_2, 18
# 9 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
.set LOCALID_MAN_4, 23
# 10 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 11 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_MapScripts::
# 12 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, BattleFrontier_OutsideWest_OnTransition
# 13 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.byte 0
# 14 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 15 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_OnTransition:
# 16 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	setvar VAR_BRAVO_TRAINER_BATTLE_TOWER_ON, 0
# 17 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	setflag FLAG_HIDE_BATTLE_TOWER_REPORTER
# 18 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 19 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 20 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_FerryAttendant::
# 21 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	lock
# 22 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	faceplayer
# 23 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_MayISeeYourTicket, MSGBOX_DEFAULT
# 24 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	checkitem ITEM_SS_TICKET
# 25 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	goto_if_eq VAR_RESULT, FALSE, BattleFrontier_OutsideWest_EventScript_NoSSTicket
# 26 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	message BattleFrontier_OutsideWest_Text_WhereWouldYouLikeToGo
# 27 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	waitmessage
# 28 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	goto BattleFrontier_OutsideWest_EventScript_ChooseFerryDestination
# 29 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 30 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 31 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_ChooseFerryDestination::
# 32 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	multichoicedefault 18, 6, MULTI_SSTIDAL_BATTLE_FRONTIER, 2, FALSE
# 33 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	switch VAR_RESULT
# 34 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	case 0, BattleFrontier_OutsideWest_EventScript_FerryToSlateport
# 35 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	case 1, BattleFrontier_OutsideWest_EventScript_FerryToLilycove
# 36 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	case 2, BattleFrontier_OutsideWest_EventScript_CancelFerrySelect
# 37 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	case MULTI_B_PRESSED, BattleFrontier_OutsideWest_EventScript_CancelFerrySelect
# 38 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 39 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 40 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_NoSSTicket::
# 41 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_MustHaveTicketToBoard, MSGBOX_DEFAULT
# 42 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	release
# 43 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 44 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 45 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_FerryToSlateport::
# 46 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_SlateportItIs, MSGBOX_YESNO
# 47 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	goto_if_eq VAR_RESULT, NO, BattleFrontier_OutsideWest_EventScript_ChooseNewFerryDestination
# 48 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_PleaseBoardFerry, MSGBOX_DEFAULT
# 49 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	call BattleFrontier_OutsideWest_EventScript_BoardFerry
# 50 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	warp MAP_SLATEPORT_CITY_HARBOR, 8, 11
# 51 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	waitstate
# 52 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	release
# 53 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 54 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 55 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_FerryToLilycove::
# 56 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_LilycoveItIs, MSGBOX_YESNO
# 57 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	goto_if_eq VAR_RESULT, NO, BattleFrontier_OutsideWest_EventScript_ChooseNewFerryDestination
# 58 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_PleaseBoardFerry, MSGBOX_DEFAULT
# 59 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	call BattleFrontier_OutsideWest_EventScript_BoardFerry
# 60 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	warp MAP_LILYCOVE_CITY_HARBOR, 8, 11
# 61 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	waitstate
# 62 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	release
# 63 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 64 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 65 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_ChooseNewFerryDestination::
# 66 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	message BattleFrontier_OutsideWest_Text_ThenWhereWouldYouLikeToGo
# 67 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	waitmessage
# 68 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	goto BattleFrontier_OutsideWest_EventScript_ChooseFerryDestination
# 69 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 70 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 71 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_BoardFerry::
# 72 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	closemessage
# 73 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	applymovement VAR_LAST_TALKED, Common_Movement_WalkInPlaceFasterDown
# 74 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	waitmovement 0
# 75 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	delay 30
# 76 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	hideobjectat LOCALID_FERRY_ATTENDANT, MAP_BATTLE_FRONTIER_OUTSIDE_WEST
# 77 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	setvar VAR_0x8004, LOCALID_SS_TIDAL
# 78 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	call Common_EventScript_FerryDepartIsland
# 79 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	return
# 80 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 81 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_CancelFerrySelect::
# 82 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_SailWithUsAnotherTime, MSGBOX_DEFAULT
# 83 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	release
# 84 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 85 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 86 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_BattleDomeSign::
# 87 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_BattleDomeSign, MSGBOX_SIGN
# 88 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 89 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 90 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_BattleFactorySign::
# 91 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_BattleFactorySign, MSGBOX_SIGN
# 92 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 93 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 94 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_BattlePikeSign::
# 95 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_BattlePikeSign, MSGBOX_SIGN
# 96 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 97 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 98 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
@ Unused. Of note, Battle Tower is in the East section in the final release
# 99 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_UnusedNPC1::
# 100 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_ThisIsBattleTower, MSGBOX_NPC
# 101 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 102 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 103 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
@ Unused
# 104 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_UnusedNPC2::
# 105 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_CantFindBattleTower, MSGBOX_NPC
# 106 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 107 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 108 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_Boy1::
# 109 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_BestOutOfAllMyFriends, MSGBOX_NPC
# 110 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 111 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 112 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_Fisherman2::
# 113 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	lock
# 114 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	faceplayer
# 115 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	message BattleFrontier_OutsideWest_Text_GotSeasickOnWayHere
# 116 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	waitmessage
# 117 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	applymovement LOCALID_FISHERMAN_2, Common_Movement_FaceAwayPlayer
# 118 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	waitmovement 0
# 119 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	waitbuttonpress
# 120 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	release
# 121 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 122 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 123 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_Man1::
# 124 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_OnlyToughTrainersBroughtHere, MSGBOX_NPC
# 125 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 126 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 127 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_Maniac1::
# 128 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	lock
# 129 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	goto BattleFrontier_OutsideWest_EventScript_FactoryChallengersTalk
# 130 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 131 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 132 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_Maniac2::
# 133 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	lock
# 134 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	goto BattleFrontier_OutsideWest_EventScript_FactoryChallengersTalk
# 135 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 136 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 137 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_FactoryChallengersTalk::
# 138 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	applymovement LOCALID_MANIAC_1, Common_Movement_WalkInPlaceFasterRight
# 139 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	waitmovement 0
# 140 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_SureWeCanChallengeWithNoMons, MSGBOX_DEFAULT
# 141 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	applymovement LOCALID_MANIAC_2, Common_Movement_WalkInPlaceFasterLeft
# 142 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	waitmovement 0
# 143 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_BigGuySaidIllLendYouMons, MSGBOX_DEFAULT
# 144 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	closemessage
# 145 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	delay 25
# 146 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	applymovement LOCALID_MANIAC_1, Common_Movement_WalkInPlaceFasterUp
# 147 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	applymovement LOCALID_MANIAC_2, Common_Movement_WalkInPlaceFasterUp
# 148 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	waitmovement 0
# 149 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	release
# 150 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 151 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 152 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_Camper::
# 153 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	lock
# 154 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	faceplayer
# 155 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	delay 20
# 156 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	call_if_eq VAR_FACING, DIR_NORTH, BattleFrontier_OutsideWest_EventScript_CamperFaceFactory
# 157 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	call_if_eq VAR_FACING, DIR_SOUTH, BattleFrontier_OutsideWest_EventScript_CamperAlreadyFacingFactory
# 158 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	call_if_eq VAR_FACING, DIR_WEST, BattleFrontier_OutsideWest_EventScript_CamperFaceFactory
# 159 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	call_if_eq VAR_FACING, DIR_EAST, BattleFrontier_OutsideWest_EventScript_CamperFaceFactory
# 160 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_WhosRaisingThoseRentalMons, MSGBOX_DEFAULT
# 161 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	release
# 162 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 163 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 164 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_CamperFaceFactory::
# 165 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	applymovement LOCALID_CAMPER, Common_Movement_WalkInPlaceFasterUp
# 166 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	waitmovement 0
# 167 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	return
# 168 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 169 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_CamperAlreadyFacingFactory::
# 170 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	return
# 171 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 172 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_Girl::
# 173 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	lock
# 174 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	faceplayer
# 175 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	message BattleFrontier_OutsideWest_Text_ScaredOfPikeBecauseSeviper
# 176 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	waitmessage
# 177 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	call_if_eq VAR_FACING, DIR_NORTH, BattleFrontier_OutsideWest_EventScript_GirlShudderNorth
# 178 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	call_if_eq VAR_FACING, DIR_SOUTH, BattleFrontier_OutsideWest_EventScript_GirlShudderSouth
# 179 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	call_if_eq VAR_FACING, DIR_WEST, BattleFrontier_OutsideWest_EventScript_GirlShudderWest
# 180 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	call_if_eq VAR_FACING, DIR_EAST, BattleFrontier_OutsideWest_EventScript_GirlShudderEast
# 181 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	waitbuttonpress
# 182 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	release
# 183 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 184 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 185 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_GirlShudderNorth::
# 186 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	applymovement LOCALID_GIRL, BattleFrontier_OutsideWest_Movement_GirlShudderNorth
# 187 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	waitmovement 0
# 188 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	return
# 189 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 190 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_GirlShudderSouth::
# 191 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	applymovement LOCALID_GIRL, BattleFrontier_OutsideWest_Movement_GirlShudderSouth
# 192 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	waitmovement 0
# 193 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	return
# 194 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 195 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_GirlShudderWest::
# 196 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	applymovement LOCALID_GIRL, BattleFrontier_OutsideWest_Movement_GirlShudderWest
# 197 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	waitmovement 0
# 198 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	return
# 199 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 200 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_GirlShudderEast::
# 201 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	applymovement LOCALID_GIRL, BattleFrontier_OutsideWest_Movement_GirlShudderEast
# 202 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	waitmovement 0
# 203 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	return
# 204 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 205 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Movement_GirlShudderNorth:
# 206 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	walk_in_place_faster_down
# 207 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	walk_in_place_faster_down
# 208 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	step_end
# 209 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 210 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Movement_GirlShudderSouth:
# 211 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	walk_in_place_faster_up
# 212 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	walk_in_place_faster_up
# 213 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	step_end
# 214 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 215 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Movement_GirlShudderWest:
# 216 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	walk_in_place_faster_right
# 217 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	walk_in_place_faster_right
# 218 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	step_end
# 219 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 220 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Movement_GirlShudderEast:
# 221 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	walk_in_place_faster_left
# 222 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	walk_in_place_faster_left
# 223 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	step_end
# 224 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 225 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_Woman2::
# 226 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	lock
# 227 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	faceplayer
# 228 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_LetsPlayRockPaperScissors, MSGBOX_DEFAULT
# 229 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	random 2
# 230 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	goto_if_eq VAR_RESULT, 1, BattleFrontier_OutsideWest_EventScript_WomanWonRockPaperScissors
# 231 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	goto BattleFrontier_OutsideWest_EventScript_WomanLostRockPaperScissors
# 232 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 233 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 234 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_WomanWonRockPaperScissors::
# 235 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_WonIllTakePikeChallenge, MSGBOX_DEFAULT
# 236 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	release
# 237 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 238 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 239 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_WomanLostRockPaperScissors::
# 240 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_LostIllPutOffPikeChallenge, MSGBOX_DEFAULT
# 241 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	release
# 242 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 243 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 244 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_Fisherman1::
# 245 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_ChooseFishingOverBattling, MSGBOX_NPC
# 246 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 247 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 248 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
@ Unused
# 249 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_UnusedNPC3::
# 250 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_DomeIsHereGrandpa, MSGBOX_NPC
# 251 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 252 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 253 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_Gentleman::
# 254 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_YoureOffToChallengeDome, MSGBOX_NPC
# 255 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 256 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 257 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_Lass::
# 258 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_KeepBattlingUntilIGetSymbol, MSGBOX_NPC
# 259 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 260 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 261 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_ExpertM::
# 262 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_WontLetGentlemenBeatMe, MSGBOX_NPC
# 263 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 264 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 265 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_Man2::
# 266 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_NothingHereNotLongAgo, MSGBOX_NPC
# 267 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 268 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 269 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_Woman1::
# 270 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_FinallyArrivedAtFrontier, MSGBOX_NPC
# 271 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 272 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 273 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_FatMan1::
# 274 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_SquareFilledWithToughPeople, MSGBOX_NPC
# 275 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 276 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 277 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_FatMan2::
# 278 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_MetOlderGirlAtPike, MSGBOX_NPC
# 279 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 280 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 281 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_Woman3::
# 282 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	lock
# 283 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_LastTimeOurEyesMet, MSGBOX_DEFAULT
# 284 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	release
# 285 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 286 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 287 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_Boy2::
# 288 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	lock
# 289 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_DomeAceLookedBecauseOfMyCheering, MSGBOX_DEFAULT
# 290 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	release
# 291 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 292 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 293 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_OldMan::
# 294 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_DomeAceIsMine, MSGBOX_NPC
# 295 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 296 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 297 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_Man4::
# 298 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	lock
# 299 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	faceplayer
# 300 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_FansOverThereUsedToBeTrainers, MSGBOX_DEFAULT
# 301 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	closemessage
# 302 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	applymovement LOCALID_MAN_4, Common_Movement_FaceOriginalDirection
# 303 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	waitmovement 0
# 304 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	release
# 305 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 306 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 307 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_EventScript_PokefanF::
# 308 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	msgbox BattleFrontier_OutsideWest_Text_MonWithLongTailInFrontier, MSGBOX_NPC
# 309 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	end
# 310 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 311 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_BattleDomeSign:
# 312 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "This is the BATTLE DOME!\n"
# 313 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Your path to the invincible superstar!$"
# 314 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 315 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_BattleFactorySign:
# 316 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "This is the BATTLE FACTORY!\n"
# 317 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Seek out the toughest POKéMON!$"
# 318 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 319 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_BattlePikeSign:
# 320 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "This is the BATTLE PIKE!\n"
# 321 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Choose one of three paths!$"
# 322 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 323 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_ThisIsBattleTower:
# 324 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "This is the BATTLE TOWER.\p"
# 325 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "TRAINERS bring their best-raised\n"
# 326 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "POKéMON for elimination-style matches.$"
# 327 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 328 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_MayISeeYourTicket:
# 329 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Hello, are you here for the ferry?\n"
# 330 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "May I see your TICKET?$"
# 331 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 332 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_MustHaveTicketToBoard:
# 333 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "{PLAYER} doesn't have the TICKET…\p"
# 334 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I'm terribly sorry.\p"
# 335 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "You must have a TICKET to board\n"
# 336 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "the ferry.$"
# 337 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 338 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_WhereWouldYouLikeToGo:
# 339 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "{PLAYER} flashed the TICKET.\p"
# 340 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Perfect! That's all you need!\p"
# 341 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "And where would you like to go?$"
# 342 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 343 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_SlateportItIs:
# 344 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "SLATEPORT CITY it is, then!$"
# 345 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 346 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_LilycoveItIs:
# 347 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "LILYCOVE CITY it is, then!$"
# 348 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 349 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_SailWithUsAnotherTime:
# 350 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Please sail with us another time!$"
# 351 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 352 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_PleaseBoardFerry:
# 353 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Please board the ferry and wait for\n"
# 354 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "departure.$"
# 355 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 356 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_ThenWhereWouldYouLikeToGo:
# 357 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Then, where would you like to go?$"
# 358 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 359 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_BestOutOfAllMyFriends:
# 360 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I'm the best out of all my friends.\n"
# 361 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "But here…\l"
# 362 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I've been useless!$"
# 363 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 364 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_CantFindBattleTower:
# 365 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I want to go to the BATTLE TOWER,\n"
# 366 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "but I can't find it even though I have\l"
# 367 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "a map of the BATTLE FRONTIER.\p"
# 368 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "This place is just too big!$"
# 369 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 370 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_GotSeasickOnWayHere:
# 371 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I wanted to take a challenge as soon\n"
# 372 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "as I arrived here.\p"
# 373 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "But on the way, I got seasick…\n"
# 374 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Urrrrp…$"
# 375 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 376 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_OnlyToughTrainersBroughtHere:
# 377 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "It's not as if just anyone can come\n"
# 378 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "here, you know?\p"
# 379 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Only those TRAINERS who've been\n"
# 380 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "recognized as tough are brought here.\p"
# 381 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "That's why many TRAINERS don't even\n"
# 382 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "know about the BATTLE FRONTIER.$"
# 383 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 384 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_SureWeCanChallengeWithNoMons:
# 385 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Hey, bro…\p"
# 386 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Are you sure we can make challenges\n"
# 387 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "even if we don't have any POKéMON?$"
# 388 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 389 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_BigGuySaidIllLendYouMons:
# 390 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Uh…\n"
# 391 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I'm sure it'll be okay.\p"
# 392 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I think…\p"
# 393 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "But remember that big scary guy?\n"
# 394 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "He said, “I'll lend you POKéMON!”$"
# 395 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 396 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_WhosRaisingThoseRentalMons:
# 397 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "That's the BATTLE FACTORY.\n"
# 398 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "You can rent strong POKéMON there.\p"
# 399 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "But it makes me wonder.\n"
# 400 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Who's raising those rental POKéMON?$"
# 401 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 402 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_ScaredOfPikeBecauseSeviper:
# 403 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I'm scared of going into the BATTLE\n"
# 404 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "PIKE because of SEVIPER…\p"
# 405 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "B-but I came all the way here, so I will\n"
# 406 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "try to conquer everything!\l"
# 407 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "…Shudder…$"
# 408 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 409 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_LetsPlayRockPaperScissors:
# 410 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Let's play rock, paper, scissors!\n"
# 411 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "One, two, three!\p"
# 412 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "… … … … … …$"
# 413 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 414 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_WonIllTakePikeChallenge:
# 415 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Yay! I won!\n"
# 416 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I will take the BATTLE PIKE challenge!$"
# 417 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 418 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_LostIllPutOffPikeChallenge:
# 419 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Oh, no…\n"
# 420 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I lost.\p"
# 421 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I guess I'm not very lucky today.\n"
# 422 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I'll put off my BATTLE PIKE challenge\l"
# 423 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "until tomorrow.$"
# 424 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 425 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_ChooseFishingOverBattling:
# 426 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I believe I'm the only person here who,\n"
# 427 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "for some unknown reason, would choose\l"
# 428 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "fishing over battling.\p"
# 429 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Huh? You can't catch anything here?\n"
# 430 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "That's disappointing…$"
# 431 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 432 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_KeepBattlingUntilIGetSymbol:
# 433 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Today, I'm going to keep battling, no\n"
# 434 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "matter what, until I get a Symbol.$"
# 435 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 436 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_YoureOffToChallengeDome:
# 437 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Oh? You're off to challenge\n"
# 438 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "the BATTLE DOME?\p"
# 439 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I'll wish you the best of luck.\n"
# 440 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Let us both win our way up and meet\l"
# 441 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "in challenges.$"
# 442 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 443 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_DomeIsHereGrandpa:
# 444 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Grandpa, over here!\n"
# 445 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "The BATTLE DOME is here!\l"
# 446 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Go get 'em, Grandpa!$"
# 447 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 448 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_WontLetGentlemenBeatMe:
# 449 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Ah, so this here is the BATTLE DOME?\n"
# 450 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I won't let GENTLEMEN beat me!\p"
# 451 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "But where is the entrance?$"
# 452 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 453 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_NothingHereNotLongAgo:
# 454 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "There used to be nothing here not all\n"
# 455 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "that long ago.\p"
# 456 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "But, now look at this place! Amazing!\n"
# 457 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I'll bring my mother out to see this.$"
# 458 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 459 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_FinallyArrivedAtFrontier:
# 460 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I've finally arrived at the BATTLE\n"
# 461 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "FRONTIER!\p"
# 462 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I'm sure to grab attention with\n"
# 463 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "my looks and ability!$"
# 464 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 465 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_SquareFilledWithToughPeople:
# 466 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Munch, munch…\p"
# 467 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "It looks like this square's filled with\n"
# 468 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "tough people.\p"
# 469 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Munch, munch…$"
# 470 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 471 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_MetOlderGirlAtPike:
# 472 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Crunch, munch…\p"
# 473 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "A while back, I met this older girl\n"
# 474 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "at the BATTLE PIKE.\p"
# 475 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "She had these eyes that were scary\n"
# 476 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "in a real ornery way.\p"
# 477 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Crunch, munch…\p"
# 478 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "She got all furious: “Will you quit\n"
# 479 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "eating!” Then she whaled on me.\p"
# 480 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "It was a hair-raising kind of\n"
# 481 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "scary experience, sure enough.\p"
# 482 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Crunch, munch…$"
# 483 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 484 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_LastTimeOurEyesMet:
# 485 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Huh? Will you listen to yourself?\n"
# 486 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "That's nothing!\p"
# 487 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Why, the last time I cheered for him,\n"
# 488 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "our eyes met and sparks flew!$"
# 489 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 490 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_DomeAceLookedBecauseOfMyCheering:
# 491 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Whaaaaaat?!\n"
# 492 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Pfft!\p"
# 493 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "That only happened because\n"
# 494 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I happened to be sitting next to you!\p"
# 495 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "The DOME ACE only looked our way\n"
# 496 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "because my cheering was so loud!$"
# 497 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 498 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_DomeAceIsMine:
# 499 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Oh, shush!\n"
# 500 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Keep that racket down!\p"
# 501 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "You fair-weather fans should stick\n"
# 502 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "to cheering for some GYM LEADER!\p"
# 503 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "The DOME ACE is mine!\n"
# 504 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "The only idol for me!$"
# 505 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 506 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_FansOverThereUsedToBeTrainers:
# 507 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Those people squabbling over there…\p"
# 508 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "It's hard to believe, but they once\n"
# 509 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "were TRAINERS, and good ones, too.\p"
# 510 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "They used to be incredibly tough,\n"
# 511 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "and they were famous, too.\p"
# 512 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "But they were obliterated by this\n"
# 513 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "certain TRAINER at a tournament.\p"
# 514 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "They were so thoroughly whipped,\n"
# 515 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "they became smitten by the TRAINER.\p"
# 516 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Now they're just fans of the TRAINER.\n"
# 517 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "They go cheer for their idol at the\l"
# 518 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "BATTLE DOME every day now.$"
# 519 "data/maps/BattleFrontier_OutsideWest/scripts.pory"

# 520 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
BattleFrontier_OutsideWest_Text_MonWithLongTailInFrontier:
# 521 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I heard a rumor that someone saw\n"
# 522 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "a POKéMON with an unusually long tail\l"
# 523 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "somewhere in the BATTLE FRONTIER.\p"
# 524 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "It must be adorable. I'm sure of it…\p"
# 525 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Oh, challenges can wait. I feel driven\n"
# 526 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "to find the delightful creature!$"
