# 1 "data/maps/FortreeCity_House3/scripts.pory"

# 2 "data/maps/FortreeCity_House3/scripts.pory"
FortreeCity_House3_MapScripts::
# 3 "data/maps/FortreeCity_House3/scripts.pory"
	.byte 0
# 4 "data/maps/FortreeCity_House3/scripts.pory"

# 5 "data/maps/FortreeCity_House3/scripts.pory"
FortreeCity_House3_EventScript_Maniac::
# 6 "data/maps/FortreeCity_House3/scripts.pory"
	msgbox FortreeCity_House3_Text_MetStevenHadAmazingPokemon, MSGBOX_NPC
# 7 "data/maps/FortreeCity_House3/scripts.pory"
	end
# 8 "data/maps/FortreeCity_House3/scripts.pory"

# 9 "data/maps/FortreeCity_House3/scripts.pory"
FortreeCity_House3_EventScript_SchoolKidM::
# 10 "data/maps/FortreeCity_House3/scripts.pory"
	msgbox FortreeCity_House3_Text_OhYouHavePokedex, MSGBOX_NPC
# 11 "data/maps/FortreeCity_House3/scripts.pory"
	end
# 12 "data/maps/FortreeCity_House3/scripts.pory"

# 13 "data/maps/FortreeCity_House3/scripts.pory"
FortreeCity_House3_Text_MetStevenHadAmazingPokemon:
# 14 "data/maps/FortreeCity_House3/scripts.pory"
	.string "While speaking about POKéDEXES,\n"
# 15 "data/maps/FortreeCity_House3/scripts.pory"
	.string "I remembered something.\p"
# 16 "data/maps/FortreeCity_House3/scripts.pory"
	.string "I met this TRAINER, STEVEN, when\n"
# 17 "data/maps/FortreeCity_House3/scripts.pory"
	.string "I was searching for rare stones.\p"
# 18 "data/maps/FortreeCity_House3/scripts.pory"
	.string "Hoo, boy, he had some amazing POKéMON\n"
# 19 "data/maps/FortreeCity_House3/scripts.pory"
	.string "with him.\p"
# 20 "data/maps/FortreeCity_House3/scripts.pory"
	.string "They weren't just rare, they were\n"
# 21 "data/maps/FortreeCity_House3/scripts.pory"
	.string "trained to terrifying extremes!\p"
# 22 "data/maps/FortreeCity_House3/scripts.pory"
	.string "He might even be stronger than the\n"
# 23 "data/maps/FortreeCity_House3/scripts.pory"
	.string "GYM LEADER in this town…$"
# 24 "data/maps/FortreeCity_House3/scripts.pory"

# 25 "data/maps/FortreeCity_House3/scripts.pory"
FortreeCity_House3_Text_OhYouHavePokedex:
# 26 "data/maps/FortreeCity_House3/scripts.pory"
	.string "What's that thing you have there?\p"
# 27 "data/maps/FortreeCity_House3/scripts.pory"
	.string "… … … … … …\p"
# 28 "data/maps/FortreeCity_House3/scripts.pory"
	.string "Oh, it's called a POKéDEX?\n"
# 29 "data/maps/FortreeCity_House3/scripts.pory"
	.string "It's really awesome!$"
