# 1 "data/maps/LilycoveCity_House4/scripts.pory"

# 2 "data/maps/LilycoveCity_House4/scripts.pory"
LilycoveCity_House4_MapScripts::
# 3 "data/maps/LilycoveCity_House4/scripts.pory"
	.byte 0
# 4 "data/maps/LilycoveCity_House4/scripts.pory"

# 5 "data/maps/LilycoveCity_House4/scripts.pory"
LilycoveCity_House4_EventScript_Man1::
# 6 "data/maps/LilycoveCity_House4/scripts.pory"
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
# 7 "data/maps/LilycoveCity_House4/scripts.pory"
	end
# 8 "data/maps/LilycoveCity_House4/scripts.pory"

# 9 "data/maps/LilycoveCity_House4/scripts.pory"
LilycoveCity_House4_EventScript_Man2::
# 10 "data/maps/LilycoveCity_House4/scripts.pory"
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
# 11 "data/maps/LilycoveCity_House4/scripts.pory"
	end
# 12 "data/maps/LilycoveCity_House4/scripts.pory"

# 13 "data/maps/LilycoveCity_House4/scripts.pory"
LilycoveCity_House4_Text_MysteriesAtBottomOfSea:
# 14 "data/maps/LilycoveCity_House4/scripts.pory"
	.string "This planet's biggest mysteries are\n"
# 15 "data/maps/LilycoveCity_House4/scripts.pory"
	.string "at the bottom of the sea.\p"
# 16 "data/maps/LilycoveCity_House4/scripts.pory"
	.string "Somebody said that, but I don't know…$"
# 17 "data/maps/LilycoveCity_House4/scripts.pory"

# 18 "data/maps/LilycoveCity_House4/scripts.pory"
LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis:
# 19 "data/maps/LilycoveCity_House4/scripts.pory"
	.string "There's a deep underwater trench\n"
# 20 "data/maps/LilycoveCity_House4/scripts.pory"
	.string "between MOSSDEEP and SOOTOPOLIS.\p"
# 21 "data/maps/LilycoveCity_House4/scripts.pory"
	.string "That's what someone told me, anyway.$"
